/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aula4;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 2830482411031
 */
public class RadioButton extends javax.swing.JFrame {

    char sexo ;
    boolean tecnologia, astronomia, esportes;
    /**
     * Creates new form RadioButton
     */
    public RadioButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnGrp_sexo = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnGrp_sexo2 = new javax.swing.JRadioButton();
        btn_Grp = new javax.swing.JRadioButton();
        btn_Salvar = new javax.swing.JButton();
        chk_astronomia = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        chk_tecnologia = new javax.swing.JCheckBox();
        chk_esportes = new javax.swing.JCheckBox();
        cmb_idioma = new javax.swing.JComboBox<>();
        idioma = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb1_pessoas = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("nome");

        jLabel2.setText("sexo");

        btnGrp_sexo.add(btnGrp_sexo2);
        btnGrp_sexo2.setText("masculino");
        btnGrp_sexo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrp_sexo2ActionPerformed(evt);
            }
        });

        btnGrp_sexo.add(btn_Grp);
        btn_Grp.setText("feminino");

        btn_Salvar.setText("salvar");
        btn_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalvarActionPerformed(evt);
            }
        });

        chk_astronomia.setText("astronomia");
        chk_astronomia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_astronomiaActionPerformed(evt);
            }
        });

        jLabel3.setText("INTERESSES");

        chk_tecnologia.setText("Tecnologia");
        chk_tecnologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_tecnologiaActionPerformed(evt);
            }
        });

        chk_esportes.setText("esportes");
        chk_esportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_esportesActionPerformed(evt);
            }
        });

        cmb_idioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pt", "en", "esp" }));

        idioma.setText("idioma");

        tb1_pessoas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nome", "sexo", "idioma"
            }
        ));
        jScrollPane3.setViewportView(tb1_pessoas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(idioma)
                        .addGap(45, 45, 45)
                        .addComponent(cmb_idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnGrp_sexo2)
                                    .addComponent(chk_tecnologia))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(chk_astronomia)
                                    .addComponent(btn_Grp))
                                .addGap(33, 33, 33)
                                .addComponent(chk_esportes))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_Salvar)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGrp_sexo2)
                            .addComponent(btn_Grp))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(chk_tecnologia)
                            .addComponent(chk_esportes)
                            .addComponent(chk_astronomia))))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idioma))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(btn_Salvar)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGrp_sexo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrp_sexo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrp_sexo2ActionPerformed

    private void btn_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalvarActionPerformed
        if(btnGrp_sexo2.isSelected()){
            sexo ='m';
            JOptionPane.showMessageDialog(null, "Sexo masculino: " +sexo, " Alerta!", JOptionPane.OK_OPTION);
        }else if(btn_Grp.isSelected()){
            sexo ='f';
            JOptionPane.showMessageDialog(null, "Sexo feminino: " +sexo, " Alerta!", JOptionPane.OK_OPTION);
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um sexo: " , " error!", JOptionPane.ERROR_MESSAGE);           
        }
        
        if(chk_tecnologia.isSelected()){
            tecnologia = true;
        }else{
            tecnologia = false;
        }
            
        if(chk_astronomia.isSelected()){
            astronomia = true;
        }else{
            astronomia = false;
        }
        if(chk_esportes.isSelected()){
            esportes = true;
        }else{
            esportes = false;
        }
        
        JOptionPane.showMessageDialog(null, "Tecnologia " +tecnologia+ " \nAstronomia!"+astronomia+" \nEsportes" +esportes, "AlertA", JOptionPane.INFORMATION_MESSAGE);      
        JOptionPane.showMessageDialog(null, "Idioma escolhido: " + cmb_idioma.getSelectedItem(), "Alerta", JOptionPane.INFORMATION_MESSAGE);
        Pessoa p = new Pessoa(txt_nome.getText(),sexo, (String) cmb_idioma.getSelectedItem());
        
        DefaultTableModel tabela = (DefaultTableModel) tb1_pessoas.getModel();
        tabela.addRow(p.obterDados());
        
        txt_nome.setText("");
        chk_tecnologia.setSelected(false);
        chk_astronomia.setSelected(false);
        chk_esportes.setSelected(false);
        cmb_idioma.setSelectedIndex(0);
    }//GEN-LAST:event_btn_SalvarActionPerformed

    private void chk_astronomiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_astronomiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_astronomiaActionPerformed

    private void chk_tecnologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_tecnologiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_tecnologiaActionPerformed

    private void chk_esportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_esportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_esportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RadioButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrp_sexo;
    private javax.swing.JRadioButton btnGrp_sexo2;
    private javax.swing.JRadioButton btn_Grp;
    private javax.swing.JButton btn_Salvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JCheckBox chk_astronomia;
    private javax.swing.JCheckBox chk_esportes;
    private javax.swing.JCheckBox chk_tecnologia;
    private javax.swing.JComboBox<String> cmb_idioma;
    private javax.swing.JLabel idioma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tb1_pessoas;
    private javax.swing.JTextField txt_nome;
    // End of variables declaration//GEN-END:variables
}
