/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aula4;

import javax.swing.JOptionPane;

/**
 *
 * @author 2830482411031
 */
public class RadioButton extends javax.swing.JFrame {

    char sexo ;
    boolean tecnologia, astronomia, esportes;
    /**
     * Creates new form RadioButton
     */
    public RadioButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnGrp_sexo = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnGrp_sexo2 = new javax.swing.JRadioButton();
        btn_Grp = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        chk_astronomia = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        chk_tecnologia = new javax.swing.JCheckBox();
        chk_esportes = new javax.swing.JCheckBox();
        cmb_idioma = new javax.swing.JComboBox<>();
        lblidioma = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("nome");

        jLabel2.setText("sexo");

        btnGrp_sexo.add(btnGrp_sexo2);
        btnGrp_sexo2.setText("masculino");
        btnGrp_sexo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrp_sexo2ActionPerformed(evt);
            }
        });

        btnGrp_sexo.add(btn_Grp);
        btn_Grp.setText("feminino");

        jButton1.setText("salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        chk_astronomia.setText("astronomia");
        chk_astronomia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_astronomiaActionPerformed(evt);
            }
        });

        jLabel3.setText("INTERESSES");

        chk_tecnologia.setText("Tecnologia");
        chk_tecnologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_tecnologiaActionPerformed(evt);
            }
        });

        chk_esportes.setText("esportes");
        chk_esportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_esportesActionPerformed(evt);
            }
        });

        cmb_idioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pt", "en", "esp", "ita" }));

        lblidioma.setText("idioma");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(lblidioma, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmb_idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chk_tecnologia)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnGrp_sexo2)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_Grp)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(chk_astronomia)
                                    .addGap(32, 32, 32)
                                    .addComponent(chk_esportes))))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnGrp_sexo2)
                    .addComponent(btn_Grp))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chk_astronomia)
                    .addComponent(jLabel3)
                    .addComponent(chk_tecnologia)
                    .addComponent(chk_esportes))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblidioma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(95, 95, 95))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGrp_sexo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrp_sexo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrp_sexo2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(btnGrp_sexo2.isSelected()){
            sexo ='m';
            JOptionPane.showMessageDialog(null, "Sexo masculino: " +sexo, " Alerta!", JOptionPane.OK_OPTION);
        }else if(btn_Grp.isSelected()){
            sexo ='f';
            JOptionPane.showMessageDialog(null, "Sexo feminino: " +sexo, " Alerta!", JOptionPane.OK_OPTION);
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um sexo: " , " error!", JOptionPane.ERROR_MESSAGE);           
        }
        
        if(chk_tecnologia.isSelected()){
            tecnologia = true;
        }else{
            tecnologia = false;
        }
            
        if(chk_astronomia.isSelected()){
            astronomia = true;
        }else{
            astronomia = false;
        }
        if(chk_esportes.isSelected()){
            esportes = true;
        }else{
            esportes = false;
        }
        
        JOptionPane.showMessageDialog(null, "Tecnologia "  +tecnologia+ " \nAstronomia!"+astronomia+" \nEsportes" +esportes, "AlertA", JOptionPane.INFORMATION_MESSAGE);
        JOptionPane.showMessageDialog(null, "Idioma escolhido: " + cmb_idioma.getSelectedItem(), "Alerta", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void chk_astronomiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_astronomiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_astronomiaActionPerformed

    private void chk_tecnologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_tecnologiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_tecnologiaActionPerformed

    private void chk_esportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_esportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_esportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RadioButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrp_sexo;
    private javax.swing.JRadioButton btnGrp_sexo2;
    private javax.swing.JRadioButton btn_Grp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JCheckBox chk_astronomia;
    private javax.swing.JCheckBox chk_esportes;
    private javax.swing.JCheckBox chk_tecnologia;
    private javax.swing.JComboBox<String> cmb_idioma;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblidioma;
    // End of variables declaration//GEN-END:variables
}
