/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.jogodavelha;

/**
 *
 * @author 2830482411031
 */
public class JogoDaVelha extends javax.swing.JFrame {

    private String jogadorAtual = "X";
    private boolean jogoAtivo = true;
    
    private void alternarJogador() {
        jogadorAtual = jogadorAtual.equals("X") ? "O" : "X";
    }
    
    public JogoDaVelha() {
        initComponents();
    }
    
    private void verificarVencedor() {
    String[][] tabuleiro = {
        {linha1coluna1.getText(), linha1coluna2.getText(), linha1coluna3.getText()},
        {linha2coluna1.getText(), linha2coluna2.getText(), linha2coluna3.getText()},
        {linha3coluna1.getText(), linha3coluna2.getText(), linha3coluna3.getText()}
    };

    for (int i = 0; i < 3; i++) {
        if (!tabuleiro[i][0].equals("") && tabuleiro[i][0].equals(tabuleiro[i][1]) && tabuleiro[i][1].equals(tabuleiro[i][2])) {
            anunciarVencedor(tabuleiro[i][0]);
            return;
        }
        // Colunas
        if (!tabuleiro[0][i].equals("") && tabuleiro[0][i].equals(tabuleiro[1][i]) && tabuleiro[1][i].equals(tabuleiro[2][i])) {
            anunciarVencedor(tabuleiro[0][i]);
            return;
        }
    }

    if (!tabuleiro[0][0].equals("") && tabuleiro[0][0].equals(tabuleiro[1][1]) && tabuleiro[1][1].equals(tabuleiro[2][2])) {
        anunciarVencedor(tabuleiro[0][0]);
        return;
    }

    if (!tabuleiro[0][2].equals("") && tabuleiro[0][2].equals(tabuleiro[1][1]) && tabuleiro[1][1].equals(tabuleiro[2][0])) {
        anunciarVencedor(tabuleiro[0][2]);
        return;
    }

    if (todasAsCasasPreenchidas()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Empate!");
        jogoAtivo = false;
    }
}

    private boolean todasAsCasasPreenchidas() {
    return !linha1coluna1.getText().equals("") &&
           !linha1coluna2.getText().equals("") &&
           !linha1coluna3.getText().equals("") &&
           !linha2coluna1.getText().equals("") &&
           !linha2coluna2.getText().equals("") &&
           !linha2coluna3.getText().equals("") &&
           !linha3coluna1.getText().equals("") &&
           !linha3coluna2.getText().equals("") &&
           !linha3coluna3.getText().equals("");
}

    
    private void anunciarVencedor(String vencedor) {
    javax.swing.JOptionPane.showMessageDialog(this, "Jogador " + vencedor + " venceu!");
    jogoAtivo = false;
}

    private void jogar(javax.swing.JButton botao) {
    if (!jogoAtivo || !botao.getText().equals("")) return;

    botao.setText(jogadorAtual);
    verificarVencedor();
    if (jogoAtivo) alternarJogador();
}
    private void reiniciarJogo() {
    linha1coluna1.setText("");
    linha1coluna2.setText("");
    linha1coluna3.setText("");
    linha2coluna1.setText("");
    linha2coluna2.setText("");
    linha2coluna3.setText("");
    linha3coluna1.setText("");
    linha3coluna2.setText("");
    linha3coluna3.setText("");
    jogadorAtual = "X";
    jogoAtivo = true;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        linha1coluna2 = new javax.swing.JButton();
        linha1coluna1 = new javax.swing.JButton();
        linha1coluna3 = new javax.swing.JButton();
        linha2coluna2 = new javax.swing.JButton();
        linha2coluna1 = new javax.swing.JButton();
        linha2coluna3 = new javax.swing.JButton();
        linha3coluna1 = new javax.swing.JButton();
        linha3coluna3 = new javax.swing.JButton();
        linha3coluna2 = new javax.swing.JButton();
        botaoReiniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        linha1coluna2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linha1coluna2ActionPerformed(evt);
            }
        });

        linha1coluna1.setActionCommand("");
        linha1coluna1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linha1coluna1ActionPerformed(evt);
            }
        });

        linha1coluna3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linha1coluna3ActionPerformed(evt);
            }
        });

        linha2coluna2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linha2coluna2ActionPerformed(evt);
            }
        });

        linha2coluna1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linha2coluna1ActionPerformed(evt);
            }
        });

        linha2coluna3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linha2coluna3ActionPerformed(evt);
            }
        });

        linha3coluna1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linha3coluna1ActionPerformed(evt);
            }
        });

        linha3coluna3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linha3coluna3ActionPerformed(evt);
            }
        });

        linha3coluna2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linha3coluna2ActionPerformed(evt);
            }
        });

        botaoReiniciar.setText("botaoReiniciar");
        botaoReiniciar.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                botaoReiniciarAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        botaoReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoReiniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(linha3coluna1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(linha2coluna1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(linha2coluna2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(linha3coluna2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(linha1coluna2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(linha1coluna3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(linha2coluna3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(linha3coluna3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoReiniciar)
                .addGap(82, 82, 82))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(76, 76, 76)
                    .addComponent(linha1coluna1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(380, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(botaoReiniciar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(linha1coluna2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(linha1coluna3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(linha2coluna3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(linha2coluna2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(linha2coluna1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(linha3coluna1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(linha3coluna2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(linha3coluna3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(61, 61, 61)
                    .addComponent(linha1coluna1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(328, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void linha3coluna2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linha3coluna2ActionPerformed
        jogar(linha3coluna2);
    }//GEN-LAST:event_linha3coluna2ActionPerformed

    private void linha3coluna3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linha3coluna3ActionPerformed
        jogar(linha3coluna3);
    }//GEN-LAST:event_linha3coluna3ActionPerformed

    private void linha3coluna1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linha3coluna1ActionPerformed
        jogar(linha3coluna1);
    }//GEN-LAST:event_linha3coluna1ActionPerformed

    private void linha2coluna3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linha2coluna3ActionPerformed
        jogar(linha2coluna3);
    }//GEN-LAST:event_linha2coluna3ActionPerformed

    private void linha2coluna2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linha2coluna2ActionPerformed
        jogar(linha2coluna2);
    }//GEN-LAST:event_linha2coluna2ActionPerformed

    private void linha2coluna1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linha2coluna1ActionPerformed
        jogar(linha2coluna1);
    }//GEN-LAST:event_linha2coluna1ActionPerformed

    private void linha1coluna3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linha1coluna3ActionPerformed
        jogar(linha1coluna3);
    }//GEN-LAST:event_linha1coluna3ActionPerformed

    private void linha1coluna2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linha1coluna2ActionPerformed
        jogar(linha1coluna2);
    }//GEN-LAST:event_linha1coluna2ActionPerformed

    private void linha1coluna1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linha1coluna1ActionPerformed
        jogar(linha1coluna1);
    }//GEN-LAST:event_linha1coluna1ActionPerformed

    private void botaoReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoReiniciarActionPerformed
       reiniciarJogo();
    }//GEN-LAST:event_botaoReiniciarActionPerformed

    private void botaoReiniciarAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_botaoReiniciarAncestorAdded
        
    }//GEN-LAST:event_botaoReiniciarAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoDaVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoDaVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoDaVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoDaVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogoDaVelha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoReiniciar;
    private javax.swing.JButton linha1coluna1;
    private javax.swing.JButton linha1coluna2;
    private javax.swing.JButton linha1coluna3;
    private javax.swing.JButton linha2coluna1;
    private javax.swing.JButton linha2coluna2;
    private javax.swing.JButton linha2coluna3;
    private javax.swing.JButton linha3coluna1;
    private javax.swing.JButton linha3coluna2;
    private javax.swing.JButton linha3coluna3;
    // End of variables declaration//GEN-END:variables
}
